server.contextPath=/service
#server.port=8085
server.port=8443
#server.contextPath=/crocs
#server.port=8088
#server.tomcat.max-threads: 4
server.tomcat.uri-encoding=UTF-8
spring.session.store-type=hash-map
security.basic.enabled=false

# s\u1ED1 thread t\u1ED1i \u0111a x\u1EED l� request
server.tomcat.threads.max=300
# thread r\u1ED7i t\u1ED1i thi\u1EC3u
server.tomcat.threads.min-spare=20
# h�ng \u0111\u1EE3i socket khi h\u1EBFt thread
server.tomcat.accept-count=200
# cho async controllers (m\u1EE5c 2)
#server.connection-timeout=30000
#spring.mvc.async.request-timeout=120
#
#
server.ssl.key-store: classpath:ieltsroom_com_pfx.pfx
server.ssl.key-store-password: L7QTCfThYG
server.ssl.keyStoreType: PKCS12


#server.ssl.keyAlias: tomcat

#server.ssl.key-store: classpath:crocsvietnamxuatkhaucom.pfx
#server.ssl.key-store-password: 123456
#server.ssl.keyStoreType: PKCS12
#server.ssl.keyAlias: tomcat

# Logging
logging.level.com.globits=DEBUG
logging.level.org: ERROR
logging.level.net: ERROR
logging.level.javax: ERROR

# ENDPOINTS CORS CONFIGURATION (EndpointCorsProperties)
endpoints.cors.allow-credentials=false
endpoints.cors.allowed-headers=Authorization, Content-Type
endpoints.cors.allowed-methods=POST, PUT, GET, OPTIONS, DELETE
#endpoints.cors.max-age=36000
endpoints.cors.max-age=60
endpoints.cors.allowed-origins=*

# MySQL connection string properties
#spring.datasource.url=jdbc:mysql://localhost:3306/taskman?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false
#spring.datasource.username=root
#spring.datasource.password=123456
#spring.datasource.driver-class-name=com.mysql.jdbc.Driver

spring.datasource.url=jdbc:sqlserver://LOCALHOST\\SQLEXPRESS;databaseName=ecommerce
#spring.datasource.url=jdbc:sqlserver://LOCALHOST\\SQLEXPRESS;databaseName=crocs
spring.datasource.username=sa
spring.datasource.password=Sqlserver!@#.
#spring.datasource.password=sql2008R2*#
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.properties.hibernate.dialect=com.globits.core.dialect.UnicodeSQLServerDialect

##------------------------------------------------------------------------------------##
## Hibernate Configurations
## For use with H2 database, set hibernate.dialect=org.hibernate.dialect.H2Dialect
## For use with MySQL database, set hibernate.dialect=org.hibernate.dialect.MySQLDialect
##------------------------------------------------------------------------------------##
# JPA (JpaBaseConfiguration, HibernateJpaAutoConfiguration)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.max_fetch_depth=3
spring.jpa.properties.hibernate.jdbc.fetch_size=50
spring.jpa.properties.hibernate.jdbc.batch_size=10
spring.jpa.properties.hibernate.c3p0.min_size=5
spring.jpa.properties.hibernate.c3p0.max_size=20
#spring.jpa.properties.hibernate.c3p0.timeout=1800
spring.jpa.properties.hibernate.c3p0.timeout=60
spring.jpa.properties.hibernate.c3p0.max_statements=50

#spring.jpa.show-sql=true
#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.tool.hbm2ddl=DEBUG
#logging.level.org.hibernate.engine.jdbc.spi.SqlExceptionHelper=DEBUG
##
#logging.level.org.hibernate.engine.jdbc.spi.SqlExceptionHelper=DEBUG
#logging.level.org.hibernate.resource.transaction=DEBUG
#logging.level.org.springframework.transaction=TRACE
#logging.level.org.springframework.orm.jpa.JpaTransactionManager=DEBUG


#multipart.max-file-size=100MB
spring.http.multipart.max-file-size=10MB

##
#spring.web.resources.cache.period=0
#spring.web.resources.chain.cache=false
##
